language: node_js
node_js:
- 10.1.0
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: npm
  email: th.kluge@me.com
  api_key:
    secure: drT9kozLL6O6aS+JzJqk1QiaGpXtRIZLZln9e7jmM+rMyO3mMDW7tVgy9B1xtXrHYkaJpC1gkD522Ze7QpgayTiQFfPsOl6NJEoxApaQn5rC4GytuimpsiagxSmOojSXlwvjZ1Ct3zmM/wj9b+zMisW5enQx0eaDNFcE581s9mGFl6oqDHigcVuugpnuinD4t0sZG/EZw/yqjQrYhv8nqD6JWdCzWTdbaqXqPe0OiT0UHfZ0TGeQnLYMLU+4GadoDgidGuwdt1FqZWxwZq8VnVNj95UY7v0KOKWi0gTBLLzPgbSN/tFFzVKROq9VIt7G1LYcGhczDGtnhe+P3h8GxDzCeTe9NP4vifA/SSYTi6ftakS/7oLWzAgNAouVL0cEQE0w0Nm1Oc32pC8giPtGSSqao/WugRAQx+Vag8m+nKapI6zJi4gjUWyNUXrfsBWO0esGYCJBocewsMVc+FuYI30zUzWSfXqqOdX8M/bO1XuU71B8d4B/+PjxTrbpq+MCUZUA6fOI7JalTyL25JdOOyt8hkqYyrSC9QYfqSk6RxcI01JKuDJUwG3OfNtDYwtSQU3n3FumGg/2U6fPNPBpHxsmDi3m+vRMmpZSFh8VlaN9MgXe4LS3lYQGNkRYHku1/NWi4MWzSNdQZkbXXHrwxvaualGAoDWsvKrkqPCUTGk=
  branch: release
  tags: true
