language: node_js
node_js:
- 10.1.0
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: npm
  email: $email
  api_key:
    secure: $secret_access_key
  on:
    branch: master